bioform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("formapp.urls")),
]

if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

formapp/urls.py
from . import views
from django.urls import path, include

app_name = "index"

urlpatterns = [
    path('', views.index, name="index"),
    path('bio-data/', views.bio_data_form, name="bio_data_form"),
]

formapp/models.py
from django.db import models


class Student(models.Model):
    # Student Information
    surname = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    student_class = models.CharField(max_length=50)
    squadron = models.CharField(max_length=50)
    svc_no = models.CharField(max_length=50)
    admission_date = models.CharField(max_length=50)
    blood_group = models.CharField(max_length=5)
    tribe = models.CharField(max_length=50)
    state_of_origin = models.CharField(max_length=50)
    lga = models.CharField(max_length=50)
    date_of_birth = models.CharField(max_length=50)
    place_of_birth = models.CharField(max_length=100)
    religion = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    hobbies = models.CharField(max_length=200)

    # Guardian/Parent Information
    guardian_parent_name = models.CharField(max_length=100)
    relationship = models.CharField(max_length=50)
    occupation = models.CharField(max_length=100)
    guardian_address = models.CharField(max_length=200)
    guardian_state_of_origin = models.CharField(max_length=50)
    telephone_no = models.CharField(max_length=15)
    next_of_kin = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

formapp/forms.py
from django import forms


class StudentForm(forms.Form):
    # Student Information
    surname = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Surname'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    student_class = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Class'}))
    squadron = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Squadron'}))
    svc_no = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'SVC No:'}))
    admission_date = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Admission Date'}))
    blood_group = forms.CharField(max_length=5, widget=forms.TextInput(attrs={'placeholder': 'Blood Group'}))
    tribe = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Tribe'}))
    state_of_origin = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'State of Origin'}))
    lga = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'L.G.A'}))
    date_of_birth = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Date of Birth'}))
    place_of_birth = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Place of Birth'}))
    religion = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Religion'}))
    address = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Address'}))
    hobbies = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Hobbies'}))

    # Guardian/Parent Information
    guardian_parent_name = forms.CharField(max_length=100,
                                           widget=forms.TextInput(attrs={'placeholder': 'Guardian/Parent Name'}))
    relationship = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Relationship'}))
    occupation = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Occupation'}))
    guardian_address = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Address'}))
    guardian_state_of_origin = forms.CharField(max_length=50,
                                               widget=forms.TextInput(attrs={'placeholder': 'State of Origin'}))
    telephone_no = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'placeholder': 'Telephone No:'}))
    next_of_kin = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Name of Next of Kin'}))

formapp/views.py
from lib2to3.fixes.fix_input import context
from .forms import StudentForm
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        "msg": "wired"
    }
    return render (request, "formapp/index.html", context, )


def bio_data_form(request):
    context = {

    }
    return render(
        request,
        "formapp/biodata.html",
        {
            "student_form": StudentForm
        }
    )

formapp/templates/formapp/biodata.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bio Form</title>
    <link type="text/css" href="{% static 'styles/style.css' %}" rel="stylesheet" />
</head>
<body>

    <main>
        <h1>Bio Data Form</h1>
        <p>Fill the form below</p>

        <h3><u>Student Information</u></h3>
        <div class="form-container">
            <div class="passport-box">
                <img src="" />
            </div>
            <div class="form-input-container">

                <form method="post">
                  <div class="long-form">
                      {{ student_form.as_p }}
                  </div>
                  {% csrf_token %}
                  <p><input type="submit" value="Submit Details"></p>

                </form>

            </div>
        </div>
    </main>

</body>
</html>

formapp/templates/formapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bio Form</title>
    <link type="text/css" href="{% static 'styles/style.css' %}" rel="stylesheet" />
</head>
<body>
    <main>
        <div class="landing-container">

            <div class="landing-container-wrap">
                <div class="landing-img-box">
                    <img src="{% static 'img/afms.png' %}" />
                </div>
                <h2>Strive to Excel</h2>
                <p>Student Bio-Data Form Application</p>
                <a href="{% url 'index:bio_data_form' %}"><button>Get Started</button></a>
            </div>
 
        </div>
    </main>
</body>
</html>

formapp/templates/formapp/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bio Form</title>
    <link type="text/css" href="../styles/style.css" rel="stylesheet" />
</head>
<body>
    <main>
        <div class="landing-container">

            <div class="landing-container-wrap">
                <div class="landing-img-box">
                    <img src="img/akintolatech.jpeg" />
                </div>
                <h2>Congratulations Victor</h2>
                <p>You have been successfully captured</p>
                <a href="../index.html"><button>Go Home</button></a>
            </div>
 
        </div>
    </main>
</body>
</html>